<a href="https://colab.research.google.com/github/lfaferreira/TCC/blob/main/TCC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import das Bibliotecas

###Estatistica e Probabilidade

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

###Google

In [ ]:
from google.colab import drive
from google.colab import files

## Leitura de arquivos

###CSV

In [ ]:
situacao_final = pd.read_csv('tabelaAlunosEscolas.csv', sep = ',')
situacao_final

,Unnamed: 0,ano,NO_ENTIDADE,ebairrnome,eescolruae,aescolnume,cescolrpae,modens,compens,anoensino,...,IN_ESP_EXCLUSIVA_MEDIO_INTEGR,IN_ESP_EXCLUSIVA_MEDIO_NORMAL,IN_COMUM_EJA_FUND,IN_COMUM_EJA_MEDIO,IN_COMUM_EJA_PROF,IN_ESP_EXCLUSIVA_EJA_FUND,IN_ESP_EXCLUSIVA_EJA_MEDIO,IN_ESP_EXCLUSIVA_EJA_PROF,IN_COMUM_PROF,IN_ESP_EXCLUSIVA_PROF
0,0,2018,ESCOLA MUNICIPAL ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,S/N,6,0,5,GRUPO V,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,2018,ESCOLA MUNICIPAL ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,S/N,6,0,5,GRUPO V,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,2018,ESCOLA MUNICIPAL ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,S/N,6,0,5,GRUPO V,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,2018,ESCOLA MUNICIPAL ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,S/N,6,0,5,GRUPO V,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,2018,ESCOLA MUNICIPAL ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,S/N,6,0,5,GRUPO V,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90741,90741,2018,ESCOLA MUNICIPAL 27 DE NOVEMBRO,COHAB,DOZE DE JUNHO,1120,6,1,4,5º ANO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
90742,90742,2018,ESCOLA MUNICIPAL 27 DE NOVEMBRO,COHAB,DOZE DE JUNHO,1120,6,1,4,5º ANO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
90743,90743,2018,ESCOLA MUNICIPAL 27 DE NOVEMBRO,COHAB,DOZE DE JUNHO,1120,6,1,4,5º ANO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
90744,90744,2018,ESCOLA MUNICIPAL 27 DE NOVEMBRO,COHAB,DOZE DE JUNHO,1120,6,1,4,5º ANO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
90745,90745,2018,ESCOLA MUNICIPAL 27 DE NOVEMBRO,COHAB,DOZE DE JUNHO,1120,6,1,4,5º ANO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

###XLSX

In [ ]:
dicionario_situacao_final = pd.read_excel('2018_dicionario_nomenclatura.xlsx')
dicionario_situacao_final = pd.DataFrame(dicionario_situacao_final)

## Lista de colunas que serão deletadas

#### Nulos

In [ ]:
atributos_nulos = [	'TP_CATEGORIA_ESCOLA_PRIVADA',
	'IN_CONVENIADA_PP',
	'TP_CONVENIO_PODER_PUBLICO',
	'IN_MANT_ESCOLA_PRIVADA_EMP',
	'IN_MANT_ESCOLA_PRIVADA_ONG',
	'IN_MANT_ESCOLA_PRIVADA_SIND',
	'IN_MANT_ESCOLA_PRIVADA_SIST_S',
	'IN_MANT_ESCOLA_PRIVADA_S_FINS',
	'CO_ESCOLA_SEDE_VINCULADA',
	'CO_IES_OFERTANTE',
	'TP_OCUPACAO_GALPAO',
	'TP_INDIGENA_LINGUA',
	'CO_LINGUA_INDIGENA',]

len(atributos_nulos)

13

####Desconsiderados

In [ ]:
atributos_desconsiderados = ['Unnamed: 0',
	'NO_ENTIDADE',
	'eescolruae',
	'aescolnume',
	'cescolrpae',
	'modens',
	'compens',
	'anoensino',
	'esermodesc',
	'nmodennome',
	'ebairrnome', 
	'esitaldesc',
	'turma',
	'ID_MATRICULA',
	'situ',
	'CO_ENTIDADE',
	'CO_ORGAO_REGIONAL',
	'TP_SITUACAO_FUNCIONAMENTO',
	'DT_ANO_LETIVO_INICIO',
	'DT_ANO_LETIVO_TERMINO',]

len(atributos_desconsiderados)

20

####Valores Unicos

In [ ]:
atributos_valores_unicos = ['ano',
	'NU_ANO_CENSO',
	'CO_REGIAO',
	'CO_MESORREGIAO',
	'CO_MICRORREGIAO',
	'CO_UF',
	'CO_MUNICIPIO',
	'CO_DISTRITO',
	'TP_DEPENDENCIA',
	'TP_LOCALIZACAO',
	'IN_LOCAL_FUNC_PREDIO_ESCOLAR',
	'IN_LOCAL_FUNC_SALAS_EMPRESA',
	'IN_LOCAL_FUNC_SOCIOEDUCATIVO',
	'IN_LOCAL_FUNC_UNID_PRISIONAL',
	'IN_LOCAL_FUNC_PRISIONAL_SOCIO',
	'IN_LOCAL_FUNC_CASA_PROFESSOR',
	'IN_LOCAL_FUNC_GALPAO',
	'IN_LOCAL_FUNC_SALAS_OUTRA_ESC',
	'IN_LOCAL_FUNC_OUTROS',
	'IN_PREDIO_COMPARTILHADO',
	'IN_AGUA_FONTE_RIO',
	'IN_AGUA_INEXISTENTE',
	'IN_ENERGIA_REDE_PUBLICA',
	'IN_ENERGIA_GERADOR',
	'IN_ENERGIA_OUTROS',
	'IN_ENERGIA_INEXISTENTE',
	'IN_ESGOTO_INEXISTENTE',
	'IN_LIXO_QUEIMA',
	'IN_LIXO_RECICLA',
	'IN_LIXO_ENTERRA',
	'IN_LIXO_OUTROS',
	'IN_LIXO_COLETA_PERIODICA',
	'IN_LIXO_JOGA_OUTRA_AREA',
	'IN_DEPENDENCIAS_OUTRAS',
	'IN_ALOJAM_ALUNO',
	'IN_ALOJAM_PROFESSOR',
	'IN_ALIMENTACAO',
	'IN_COMPUTADOR',
	'IN_INTERNET',
	'TP_LOCALIZACAO_DIFERENCIADA',
	'IN_MATERIAL_ESP_QUILOMBOLA',
	'IN_MATERIAL_ESP_INDIGENA',
	'IN_MATERIAL_ESP_NAO_UTILIZA',
	'IN_EDUCACAO_INDIGENA',
	'IN_FORMACAO_ALTERNANCIA',
	'IN_MEDIACAO_PRESENCIAL',
	'IN_MEDIACAO_SEMIPRESENCIAL',
	'IN_MEDIACAO_EAD',
	'IN_ESPECIAL_EXCLUSIVA',
	'IN_REGULAR',
	'IN_PROFISSIONALIZANTE',
	'IN_COMUM_MEDIO_MEDIO',
	'IN_COMUM_MEDIO_INTEGRADO',
	'IN_COMUM_MEDIO_NORMAL',
	'IN_ESP_EXCLUSIVA_CRECHE',
	'IN_ESP_EXCLUSIVA_PRE',
	'IN_ESP_EXCLUSIVA_FUND_AI',
	'IN_ESP_EXCLUSIVA_FUND_AF',
	'IN_ESP_EXCLUSIVA_MEDIO_MEDIO',
	'IN_ESP_EXCLUSIVA_MEDIO_INTEGR',
	'IN_ESP_EXCLUSIVA_MEDIO_NORMAL',
	'IN_COMUM_EJA_MEDIO',
	'IN_COMUM_EJA_PROF',
	'IN_ESP_EXCLUSIVA_EJA_FUND',
	'IN_ESP_EXCLUSIVA_EJA_MEDIO',
	'IN_ESP_EXCLUSIVA_EJA_PROF',
	'IN_COMUM_PROF',
	'IN_ESP_EXCLUSIVA_PROF',]

len(atributos_valores_unicos)

68

#### Numericos

In [ ]:
numericos = ['TP_REGULAMENTACAO',
	'TP_OCUPACAO_PREDIO_ESCOLAR',
	'QT_SALAS_EXISTENTES',
	'QT_SALAS_UTILIZADAS',
	'QT_EQUIP_TV',
	'QT_EQUIP_VIDEOCASSETE',
	'QT_EQUIP_DVD',
	'QT_EQUIP_PARABOLICA',
	'QT_EQUIP_COPIADORA',
	'QT_EQUIP_RETROPROJETOR',
	'QT_EQUIP_IMPRESSORA',
	'QT_EQUIP_IMPRESSORA_MULT',
	'QT_EQUIP_SOM',
	'QT_EQUIP_MULTIMIDIA',
	'QT_EQUIP_FAX',
	'QT_EQUIP_FOTO', 
	'QT_COMPUTADOR',
	'QT_COMP_ADMINISTRATIVO',
	'QT_COMP_ALUNO', 
	'QT_FUNCIONARIOS']

#### Valores dispensavis após limpeza

In [ ]:
valores_dispensaveis_apos_filtragem = ['IN_AGUA_CACIMBA',
                                       'IN_EJA', 
                                       'IN_COMUM_EJA_FUND']

len(valores_dispensaveis_apos_filtragem)

3

#### truno

In [ ]:
turno = ['nturesnome']

In [ ]:
situacao_final['esitaldesc'].unique()

array(['APROVADO', 'TR DUR ANO FORA REDE', 'RETIDO', 'REPROV P/  FALTA',
       'FALECIDO', 'REMANEJADO', 'DESIST/DEIXOU FREQUE',
       'TR DUR ANO P/REDE', 'RENV S/SIT FINAL DEF', 'NUNCA COMPARECEU',
       'DESISTENTE RENOVADO', 'DESIST REN C/ TRANSF', 'TR DUR ANO S/INFO',
       'RETIDO E TR P/ REDE'], dtype=object)

## Manipulação de Dados

### Remoção Inicial

In [ ]:
colunas_deletadas = [atributos_nulos, atributos_desconsiderados, atributos_valores_unicos, valores_dispensaveis_apos_filtragem]

In [ ]:
def drop_atributos(columns):
  situacao_final.drop(columns, axis = 1, inplace = True)

In [ ]:
def drop_rows(columns):
  for index in range(len(dicionario_situacao_final)):
    if dicionario_situacao_final.nome[index] in colunas_deletadas:
      dicionario_situacao_final.drop(index, inplace=True)

In [ ]:
drop_atributos(atributos_nulos)

### Drop de rows nulos

In [ ]:
situacao_final.dropna(inplace=True)

In [ ]:
data_quantidade = pd.DataFrame(situacao_final[numericos])
drop_atributos(numericos)

### Agrupamento de Bairros

In [ ]:
condList = [
    #RPA1
    (situacao_final['ebairrnome'] == "SANTO AMARO") | (situacao_final['ebairrnome'] == "BOA VISTA")
    | (situacao_final['ebairrnome'] == "RECIFE")
    | (situacao_final['ebairrnome'] == "CABANGA") | (situacao_final['ebairrnome'] == "ILHA DO LEITE")
    | (situacao_final['ebairrnome'] == "PAISSANDU") | (situacao_final['ebairrnome'] == "SANTO ANTONIO")
    | (situacao_final['ebairrnome'] == "SAO JOSE") | (situacao_final['ebairrnome'] == "COELHOS")
    | (situacao_final['ebairrnome'] == "SOLEDADE") | (situacao_final['ebairrnome'] == "ILHA JOANA BEZERRA")
    #RPA2
    , (situacao_final['ebairrnome'] == "ARRUDA") | (situacao_final['ebairrnome'] == "CAMPINA DO BARRETO")
    | (situacao_final['ebairrnome'] == "ENCRUZILHADA") | (situacao_final['ebairrnome'] == "HIPODROMO")
    | (situacao_final['ebairrnome'] == "PEIXINHOS") | (situacao_final['ebairrnome'] == "PONTO DE PARADA")
    | (situacao_final['ebairrnome'] == "ROSARINHO") | (situacao_final['ebairrnome'] == "TORREAO")
    | (situacao_final['ebairrnome'] == "AGUA FRIA") | (situacao_final['ebairrnome'] == "ALTO SANTA TEREZINHA")
    | (situacao_final['ebairrnome'] == "BOMBA DO HEMETERIO") | (situacao_final['ebairrnome'] == "CAJUEIRO")
    | (situacao_final['ebairrnome'] == "FUNDAO") | (situacao_final['ebairrnome'] == "PORTO DA MADEIRA")
    | (situacao_final['ebairrnome'] == "BEBERIBE") | (situacao_final['ebairrnome'] == "DOIS UNIDOS")
    | (situacao_final['ebairrnome'] == "LINHA DO TIRO") | (situacao_final['ebairrnome'] == "CAMPO GRANDE")
    #RPA3
    ,(situacao_final['ebairrnome'] == "AFLITOS") | (situacao_final['ebairrnome'] == "ALTO DO MANDU")
    | (situacao_final['ebairrnome'] == "BREJO DE BEBERIBE")
    | (situacao_final['ebairrnome'] == "ALTO JOSE BONIFACIO") | (situacao_final['ebairrnome'] == "ALTO JOSE DO PINHO")
    | (situacao_final['ebairrnome'] == "APIPUCOS") | (situacao_final['ebairrnome'] == "BREJO DA GUABIRABA")
    | (situacao_final['ebairrnome'] == "CASA AMARELA") | (situacao_final['ebairrnome'] == "CASA FORTE")
    | (situacao_final['ebairrnome'] == "CORREGO DO JENIPAPO") | (situacao_final['ebairrnome'] == "DERBY")
    | (situacao_final['ebairrnome'] == "DOIS IRMAOS") | (situacao_final['ebairrnome'] == "ESPINHEIRO")
    | (situacao_final['ebairrnome'] == "GRACAS") | (situacao_final['ebairrnome'] == "GUABIRABA")
    | (situacao_final['ebairrnome'] == "JAQUEIRA") | (situacao_final['ebairrnome'] == "MACAXEIRA")
    | (situacao_final['ebairrnome'] == "MONTEIRO") | (situacao_final['ebairrnome'] == "NOVA DESCOBERTA")
    | (situacao_final['ebairrnome'] == "PARNAMIRIM") | (situacao_final['ebairrnome'] == "PASSARINHO")
    | (situacao_final['ebairrnome'] == "POCO DA PANELA") | (situacao_final['ebairrnome'] == "SANTANA")
    | (situacao_final['ebairrnome'] == "SITIO DOS PINTOS") | (situacao_final['ebairrnome'] == "TAMARINEIRA")
    | (situacao_final['ebairrnome'] == "MANGABEIRA") | (situacao_final['ebairrnome'] == "MORRO DA CONCEICAO")
    | (situacao_final['ebairrnome'] == "VASCO DA GAMA")
    #RPA4
    ,(situacao_final['ebairrnome'] == "ILHA DO RETIRO") | (situacao_final['ebairrnome'] == "CORDEIRO")
    |(situacao_final['ebairrnome'] == "IPUTINGA") | (situacao_final['ebairrnome'] == "MADALENA")
    |(situacao_final['ebairrnome'] == "PRADO") | (situacao_final['ebairrnome'] == "TORRE")
    |(situacao_final['ebairrnome'] == "ZUMBI") | (situacao_final['ebairrnome'] == "ENGENHO DO MEIO")
    |(situacao_final['ebairrnome'] == "TORROES") | (situacao_final['ebairrnome'] == "CAXANGA")
    |(situacao_final['ebairrnome'] == "CANXANGA") | (situacao_final['ebairrnome'] == "VARZEA")
    #RPA5
    ,(situacao_final['ebairrnome'] == "AFOGADOS") | (situacao_final['ebairrnome'] == "AREIAS")
    |(situacao_final['ebairrnome'] == "BARRO") | (situacao_final['ebairrnome'] == "BONGI")
    |(situacao_final['ebairrnome'] == "CACOTE") | (situacao_final['ebairrnome'] == "COQUEIRAL")
    |(situacao_final['ebairrnome'] == "CURADO") | (situacao_final['ebairrnome'] == "ESTANCIA")
    |(situacao_final['ebairrnome'] == "JARDIM SAO PAULO") | (situacao_final['ebairrnome'] == "JIQUIA")
    |(situacao_final['ebairrnome'] == "MANGUEIRA") | (situacao_final['ebairrnome'] == "MUSTARDINHA")
    |(situacao_final['ebairrnome'] == "SAN MARTIN") | (situacao_final['ebairrnome'] == "SANCHO")
    |(situacao_final['ebairrnome'] == "TEJIPIO") | (situacao_final['ebairrnome'] == "TOTO")
    #RPA6
    ,(situacao_final['ebairrnome'] == "BOA VIAGEM") | (situacao_final['ebairrnome'] == "BRASILIA TEIMOSA")
    |(situacao_final['ebairrnome'] == "IMBIRIBEIRA") | (situacao_final['ebairrnome'] == "IPSEP")
    |(situacao_final['ebairrnome'] == "PINA") | (situacao_final['ebairrnome'] == "IBURA")
    |(situacao_final['ebairrnome'] == "JORDAO") | (situacao_final['ebairrnome'] == "COHAB")
]

choicelist = ["RPA1", "RPA2", "RPA3", "RPA4", "RPA5", "RPA6"]
situacao_final['RPA'] = np.select(condList, choicelist)

### Definindo Fracasso Escolar

In [ ]:
condition_list = [
    #N
    (situacao_final['esitaldesc'] == "APROVADO") | 
    (situacao_final['esitaldesc'] == "TR DUR ANO FORA REDE") | 
    (situacao_final['esitaldesc'] == "TR DUR ANO P/REDE") | 
    (situacao_final['esitaldesc'] == "REMANEJADO") | 
    (situacao_final['esitaldesc'] == "TR DUR ANO S/INFO"),
    #Y
    (situacao_final['esitaldesc'] == "RETIDO") | 
    (situacao_final['esitaldesc'] == "REPROV P/ FALTA	")| 
    (situacao_final['esitaldesc'] == "RETIDO E TR P/ REDE") | 
    (situacao_final['esitaldesc'] == "DESIST/DEIXOU FREQUE") | 
    (situacao_final['esitaldesc'] == "DESISTENTE RENOVADO") | 
    (situacao_final['esitaldesc'] == "DESIST REN C/ TRANSF")
]

choicelist = ['N', 'S']
situacao_final['FRACASSO'] = np.select(condition_list, choicelist)

### Removendo Alunos que não tiveram ano letivo

In [ ]:
situacao_final = situacao_final[situacao_final.esitaldesc != 'FALECIDO']
situacao_final = situacao_final[situacao_final.esitaldesc != 'RN']
situacao_final = situacao_final[situacao_final.esitaldesc != 'RENV S/SIT FINAL DEF']

### Separando apenas EJA

In [ ]:
situacao_final = situacao_final.query('IN_EJA == 1')

### Drop Colunas Indesejadas

In [ ]:
drop_atributos(atributos_desconsiderados)
drop_atributos(atributos_valores_unicos)
# drop_atributos(numericos)
drop_atributos(valores_dispensaveis_apos_filtragem)

drop_rows(colunas_deletadas)

### Transformando dados Numericos em Categoricos

In [ ]:
situacao_final = situacao_final.apply(lambda x: x.astype(str).str.replace('1.0', 'S'))
situacao_final = situacao_final.apply(lambda x: x.astype(str).str.replace('0.0', 'N'))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

### Transformando caracter especial em normal

In [ ]:
situacao_final = situacao_final.apply(lambda x: x.astype(str).str.replace('Ã', 'A'))
situacao_final = situacao_final.apply(lambda x: x.astype(str).str.replace('ã', 'a'))

###Merge dos dados numericos

In [ ]:
situacao_final = situacao_final.join(data_quantidade)

###Limpeza final

In [ ]:
situacao_final = situacao_final[situacao_final.RPA != "0"]
situacao_final = situacao_final[situacao_final.FRACASSO != "0"]
situacao_final = pd.DataFrame(situacao_final)

## Base Final pré-processada

In [ ]:
situacao_final

,nturesnome,alunosexo,IN_LOCAL_FUNC_TEMPLO_IGREJA,IN_AGUA_FILTRADA,IN_AGUA_REDE_PUBLICA,IN_AGUA_POCO_ARTESIANO,IN_ESGOTO_REDE_PUBLICA,IN_ESGOTO_FOSSA,IN_SALA_DIRETORIA,IN_SALA_PROFESSOR,...,QT_EQUIP_IMPRESSORA,QT_EQUIP_IMPRESSORA_MULT,QT_EQUIP_SOM,QT_EQUIP_MULTIMIDIA,QT_EQUIP_FAX,QT_EQUIP_FOTO,QT_COMPUTADOR,QT_COMP_ADMINISTRATIVO,QT_COMP_ALUNO,QT_FUNCIONARIOS
0,MANHA,M,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
1,MANHA,M,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
2,MANHA,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
3,MANHA,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
4,MANHA,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90313,NOITE,M,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90314,NOITE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90315,NOITE,M,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90316,NOITE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90317,NOITE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0

In [ ]:
sim = pd.DataFrame(situacao_final.query('FRACASSO == "S"'))

In [ ]:
sim

,nturesnome,alunosexo,IN_LOCAL_FUNC_TEMPLO_IGREJA,IN_AGUA_FILTRADA,IN_AGUA_REDE_PUBLICA,IN_AGUA_POCO_ARTESIANO,IN_ESGOTO_REDE_PUBLICA,IN_ESGOTO_FOSSA,IN_SALA_DIRETORIA,IN_SALA_PROFESSOR,...,QT_EQUIP_IMPRESSORA,QT_EQUIP_IMPRESSORA_MULT,QT_EQUIP_SOM,QT_EQUIP_MULTIMIDIA,QT_EQUIP_FAX,QT_EQUIP_FOTO,QT_COMPUTADOR,QT_COMP_ADMINISTRATIVO,QT_COMP_ALUNO,QT_FUNCIONARIOS
104,MANHA,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
112,MANHA,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
125,MANHA,M,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
130,MANHA,M,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
143,TARDE,M,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90305,NOITE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90309,NOITE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90310,NOITE,M,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90311,NOITE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90316,NOITE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0

## Filtragem Pelo turno da Noite

### Filtragem de dados

In [ ]:
situacao_final = situacao_final.query('nturesnome == "NOITE"')

In [ ]:
situacao_final

,nturesnome,alunosexo,IN_LOCAL_FUNC_TEMPLO_IGREJA,IN_AGUA_FILTRADA,IN_AGUA_REDE_PUBLICA,IN_AGUA_POCO_ARTESIANO,IN_ESGOTO_REDE_PUBLICA,IN_ESGOTO_FOSSA,IN_SALA_DIRETORIA,IN_SALA_PROFESSOR,...,QT_EQUIP_IMPRESSORA,QT_EQUIP_IMPRESSORA_MULT,QT_EQUIP_SOM,QT_EQUIP_MULTIMIDIA,QT_EQUIP_FAX,QT_EQUIP_FOTO,QT_COMPUTADOR,QT_COMP_ADMINISTRATIVO,QT_COMP_ALUNO,QT_FUNCIONARIOS
284,NOITE,M,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
285,NOITE,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
286,NOITE,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
287,NOITE,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
288,NOITE,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90313,NOITE,M,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90314,NOITE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90315,NOITE,M,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90316,NOITE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90317,NOITE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0

### Remoção de dados

In [ ]:
drop_atributos(turno)

## Filtragem SEM o turno da noite

### Filtragem de dados

In [ ]:
situacao_final = situacao_final.query('nturesnome != "NOITE"')

In [ ]:
situacao_final

,nturesnome,alunosexo,IN_LOCAL_FUNC_TEMPLO_IGREJA,IN_AGUA_FILTRADA,IN_AGUA_REDE_PUBLICA,IN_AGUA_POCO_ARTESIANO,IN_ESGOTO_REDE_PUBLICA,IN_ESGOTO_FOSSA,IN_SALA_DIRETORIA,IN_SALA_PROFESSOR,...,QT_EQUIP_IMPRESSORA,QT_EQUIP_IMPRESSORA_MULT,QT_EQUIP_SOM,QT_EQUIP_MULTIMIDIA,QT_EQUIP_FAX,QT_EQUIP_FOTO,QT_COMPUTADOR,QT_COMP_ADMINISTRATIVO,QT_COMP_ALUNO,QT_FUNCIONARIOS
0,MANHA,M,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
1,MANHA,M,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
2,MANHA,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
3,MANHA,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
4,MANHA,F,N,S,S,N,N,S,S,N,...,0.0,2.0,0.0,1.0,0.0,0.0,3.0,0.0,3.0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90297,TARDE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90298,TARDE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90299,TARDE,M,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90300,TARDE,F,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0
90301,TARDE,M,N,S,S,N,S,N,S,S,...,0.0,3.0,5.0,1.0,0.0,0.0,12.0,3.0,9.0,52.0

### Remoção de dados

In [ ]:
drop_atributos(turno)

## Renomar Colunas para rodar no algoritmo de subgupos

In [ ]:
nomes_antigos = dicionario_situacao_final['nome']
novos_nomes = dicionario_situacao_final['Dicionario']

In [ ]:
for index in range(len(novos_nomes)):
  situacao_final.rename({nomes_antigos.iloc[index] : novos_nomes.iloc[index]},
                        axis=1,
                        inplace =True)

## Download da  Base

### Base CSV

In [ ]:
situacao_final.to_csv('base_dados_pre_processada.csv')

In [ ]:
files.download("base_dados_pre_processada.csv")

### Base xlsx

In [ ]:
situacao_final.to_excel('base_dados_pre_processada.xlsx')

In [ ]:
files.download("base_dados_pre_processada.xlsx")